### ISSUE TITLE
Add a code of conduct

### ISSUE THREAD

**Issue by crawfoal** [MilSpouseCoders/milspousecoders#17]

**Comment by toanhtran** [comment]
I started a code of conduct. But I need some input and a review. https://github.com/MilSpouseCoders/code-of-conduct.md

**Comment by crawfoal** [comment]
GitHub has Code of Conduct templates that you can choose from if you create the file on GitHub.com and name the file `CODE_OF_CONDUCT.md`, should we just use that?

Otherwise, I can take a look at the one you wrote.

**Comment by toanhtran** [comment]
Lets use the one on GitHub.com
