### ISSUE TITLE
Should we continue to use both Minitest and RSpec?

### ISSUE THREAD

**Issue by crawfoal** [MilSpouseCoders/milspousecoders#22]
Right now the project is set up with both, so I'm setting up Semaphore to run both suites. My gut says no, we should not use both technologies. If this was done on purpose, I'm apprehensive but open to the idea.

**Comment by crawfoal** [comment]
@codeByScott what are your thoughts?

**Comment by codeByScott** [comment]
@crawfoal which one do you prefer. I am not very experienced in either.

**Comment by crawfoal** [comment]
I prefer RSpec. I haven't used Minitest in a long time 🙂

**Comment by crawfoal** [comment]
Okay, I'll get RSpec all set up.
