### ISSUE TITLE
Instructions for adding a remote don't work

### ISSUE THREAD

**Issue by crawfoal** [MilSpouseCoders/milspousecoders#8]
I followed the instructions to add the main repo as a remote, and it didn't work. It said I didn't have permissions.

Using https://github.com/MilSpouseCoders/milspousecoders.git instead of the link listed worked (this comes from clone and download button).

**Comment by codeByScott** [comment]
@crawfoal would you mind making the change? 

Were you able to get everything working fine on your system after using the **https** link?

**Comment by crawfoal** [comment]
Yes, I can make the change - I'll assign this to myself, and then fix it soon :) And yes - everything worked fine once I used that link.
